name: assemble-app
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  get-pr-number:
    if: github.event_name == 'pull_request'
    name: "get-pr-number"
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.pull_request.number }}
        run: echo ok
  assemble:
    if: >
      github.event_name == 'push' || 
      github.event_name == 'pull_request' && 
      !contains(github.event.pull_request.head.ref, 'main')
    name: "assemble android application files"
    runs-on: ubuntu-latest
    steps:
      - name: Get HEAD to fetch
        id: fetch-head
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "::set-output name=ref::${{ github.ref }}"
          else
            echo "::set-output name=ref::refs/pull/${{ github.event.pull_request.number }}/merge"
          fi
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.fetch-head.outputs.ref }}
      - run: rm -fr ./gh-actions
      - uses: actions/checkout@v2
        with:
          ref: gh-actions
          path: gh-actions
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: bundleDebug
          dependencies-cache-key: |
            **/*.gradle
            **/*.gradle.kts
            buildSrc/src/**/*.kt
            **/gradle.properties
            gradle/**
      - uses: actions/upload-artifact@v2
        with:
          name: assemble-output
          path: android/build/outputs
          retention-days: 14
  test:
    if: >
      github.event_name == 'push' || 
      github.event_name == 'pull_request' && 
      !contains(github.event.pull_request.head.ref, 'main')
    name: "test on feature branches"
    runs-on: ubuntu-latest
    steps:
      - name: Get HEAD to fetch
        id: fetch-head
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "::set-output name=ref::${{ github.ref }}"
          else
            echo "::set-output name=ref::refs/pull/${{ github.event.pull_request.number }}/merge"
          fi
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.fetch-head.outputs.ref }}
      - run: rm -fr ./gh-actions
      - uses: actions/checkout@v2
        with:
          ref: gh-actions
          path: gh-actions
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: testDebugUnitTest
          dependencies-cache-key: |
            **/*.gradle
            **/*.gradle.kts
            buildSrc/src/**/*.kt
            **/gradle.properties
            gradle/**
      - uses: actions/upload-artifact@v2
        with:
          name: unit-test-reports
          path: "./**/reports"
          retention-days: 14
  stage-default:
    if: github.event_name == 'push'
    needs: [assemble]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: gh-actions
          path: gh-actions
      - uses: actions/download-artifact@v2
        with:
          name: assemble-output
          path: ~/assemble-output
      - uses: ./gh-actions/actions/find-files
        id: find-aab-files
        with:
          pattern: "~/assemble-output/**/*.aab"
      - uses: jmatsu/dg-upload-app-action@v0.2
        id: upload
        with:
          app_owner_name: droidkaigi
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          app_file_path: ${{ fromJSON(steps.find-aab-files.outputs.paths)[0] }}
          message: GitHub Actions have staged an artifact of ${{ github.ref }} / ${{ github.sha }}
          distribution_find_by: name
          distribution_id: ${{ format('staging/{0}', github.ref) }}
          release_note: ${{ format('[main] Workflow {0}/{1} based on {2}', github.run_id , github.run_number , github.sha) }}
          pin: false
